
DROP DATABASE IF EXISTS danhsachbanhang;

CREATE DATABASE IF NOT EXISTS danhsachbanhang;
USE danhsachbanhang;

-- Tạo bảng KHACHHANG
CREATE TABLE KHACHHANG (
    MAKH INT PRIMARY KEY,
    HOTEN VARCHAR(255),
    DCHI VARCHAR(255),
    SODT VARCHAR(15),
    NGSINH DATE,
    DOANHSO DECIMAL(18,2),
    NGDK DATE
);

-- Tạo bảng NHANVIEN
CREATE TABLE NHANVIEN (
    MANV INT PRIMARY KEY,
    HOTEN VARCHAR(255),
    NGVL DATE,
    SODT VARCHAR(15)
);

-- Tạo bảng SANPHAM
CREATE TABLE SANPHAM (
    MASP INT PRIMARY KEY,
    TENSP VARCHAR(255),
    DVT VARCHAR(20),
    NUOCSX VARCHAR(50),
    GIA DECIMAL(18,2)
);

-- Tạo bảng HOADON
CREATE TABLE HOADON (
    SOHD INT PRIMARY KEY,
    NGHD DATE,
    MAKH INT,
    MANV INT,
    TRIGIA DECIMAL(18,2),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- Tạo bảng CTHD
CREATE TABLE CTHD (
    SOHD INT,
    MASP INT,
    SL INT,
    PRIMARY KEY (SOHD, MASP),
    FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);

-- Thêm thuộc tính GHICHU có kiểu dữ liệu varchar(20) cho quan hệ SANPHAM
ALTER TABLE SANPHAM
ADD GHICHU VARCHAR(20);

-- Thêm thuộc tính LOAIKH có kiểu dữ liệu tinyint cho quan hệ KHACHHANG
ALTER TABLE KHACHHANG
ADD LOAIKH TINYINT;

-- Sửa kiểu dữ liệu của thuộc tính GHICHU trong quan hệ SANPHAM thành varchar(100)
ALTER TABLE SANPHAM 
MODIFY COLUMN GHICHU VARCHAR(100);


-- Xóa thuộc tính GHICHU trong quan hệ SANPHAM
ALTER TABLE SANPHAM
DROP COLUMN GHICHU;

-- Đặt ràng buộc cho thuộc tính LOAIKH trong quan hệ KHACHHANG
ALTER TABLE KHACHHANG
ADD CONSTRAINT LOAIKH CHECK (LOAIKH IN (1, 2, 3)); -- 1: Vang lai, 2: Thuong xuyen, 3: Vip

-- Ràng buộc cho ĐVT của sản phẩm
ALTER TABLE SANPHAM
ADD CONSTRAINT DVT CHECK (DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'));

-- Ràng buộc cho GIA của sản phẩm
ALTER TABLE SANPHAM
ADD CONSTRAINT GIA CHECK (GIA >= 500);

-- Ràng buộc cho SL trong CTHD
ALTER TABLE CTHD
ADD CONSTRAINT CK_SL CHECK (SL >= 1);

-- Ràng buộc cho NGDK trong KHACHHANG
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_NGDK_NGSINH CHECK (NGDK > NGSINH);

-- Ràng buộc cho NGHD trong HOADON và NHANVIEN
ALTER TABLE HOADON
ADD CONSTRAINT CK_NGHD_NGVL CHECK (NGHD >= NGDK);

ALTER TABLE NHANVIEN
ADD CONSTRAINT CK_NGVL CHECK (NGVL <= NGHD);

-- Ràng buộc cho CTHD và HOADON
ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_SOHD FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD);

ALTER TABLE HOADON
ADD CONSTRAINT CK_HOADON_CTHD CHECK (EXISTS (SELECT 1 FROM CTHD WHERE CTHD.SOHD = HOADON.SOHD));
